## SIGNS CONFIGURATION #######################################################################
## If you used &0 as first color, you don't need to write it. Example: &lTEST = &0&lTEST.  ##
## Si usas &0 como primer color, no debes escribirlo. Ejemplo: &lTEST = &0&lTEST.         ##
###########################################################################################
signs:
  admin-setup-name: "[kitpvp]"
  lines:
    first-line: "&l✼ KitPvP ✼"
    second-line: "&5Selecciona tu &lKIT"
    third-line: ""
    fourth-line: "&8Dale Clic"

## MESSAGES ###################################################################
## All the plugin messages.                                                 ##
## Todos los mensajes del plugin estan aqui.                               ##
############################################################################